- name: Add Node packages to yum
  shell: curl -fsSL https://rpm.nodesource.com/setup_21.x | bash -

- name: Install Node.js
  yum:
    name: nodejs
    state: present

- name: Copy sample app
  copy:
    src: app.js
    dest: /home/ec2-user/app.js
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Start sample app
  shell: nohup node /home/ec2-user/app.js &
  args:
    chdir: /home/ec2-user/
    creates: /tmp/node-app.pid
