name: Tofu Apply

on:
  push:
    branches: ["main"]
    paths: ["td5/scripts/tofu/live/lambda-sample/**"]

jobs:
  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: read

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Configure AWS credentials via OIDC
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.APPLY_ROLE_ARN }}
          role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      # 3. Setup OpenTofu
      - uses: opentofu/setup-opentofu@v1

      # 4. Run OpenTofu apply
      - name: Tofu apply
        id: apply
        working-directory: td5/scripts/tofu/live/lambda-sample
        run: |
          tofu init -no-color -input=false
          tofu apply -no-color -input=false -lock-timeout=60m -auto-approve

      # 5. Find current PR
      - name: Find current PR
        uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: all

      # 6. Comment apply output on PR
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        if: steps.find_pr.outputs.number
        env:
          RESULT_EMOJI: ${{ steps.apply.outcome == 'success' && '✅' || '⚠' }}
        with:
          issue-number: ${{ steps.find_pr.outputs.number }}
          body: |

            ```
            ${{ steps.apply.outputs.stdout }}
            ```
